# Generated by Django 5.0.2 on 2024-02-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_image_user_phone_user_town_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': ('User',), 'verbose_name_plural': 'Users'},
        ),
    ]
