# Generated by Django 5.0.2 on 2024-03-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_payment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('user', 'date_of_payment', 'paid_course', 'paid_lesson'), 'verbose_name': 'paid', 'verbose_name_plural': 'paids'},
        ),
    ]
