# Generated by Django 5.0.2 on 2024-03-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_payment_amount_alter_payment_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(verbose_name='payment amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], max_length=20, verbose_name='payment method'),
        ),
    ]
