# Generated by Django 5.0.2 on 2024-02-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='course/preview/', verbose_name='preview'),
        ),
    ]
