# Generated by Django 5.0.2 on 2024-03-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=100, verbose_name='Amount in kopecks'),
        ),
    ]
